### ISSUE TITLE
URL parsing bug

### ISSUE THREAD

**Issue by rmisev** [ada-url/playground#5]
I opened the URL Parser Playground https://playground.ada-url.com/, entered the following URL: `http://host?a=a&b=b#frag` and got an incorrect result:
> Input resolved into "http://host/?a=a"

When I press the "Parse" button again, the result is already good:
> Input resolved into "http://host/?a=a&b=b#frag"

**Comment by lemire** [comment]
Verified. There is a bug.

cc @anonrig

**Comment by anonrig** [comment]
Thank you for the bug report @rmisev. This was caused by `#` breaking the search parameter of the URL. I've fixed this issue in the new playground which will be available under the repository: https://github.com/ada-url/website

**Comment by anonrig** [comment]
Example url to fix this issue: https://ada-url.vercel.app/playground?url=http%3A%2F%2Fhost%3Fa%3Da%26b%3Db%23frag
